edoc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('posts.urls' , namespace="posts"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import list_view, detail_view, search_view

urlpatterns = [
    url(r'^$', list_view, name="home" ),
    url(r'^detail/(?P<slug>.+)$', detail_view, name="detail" ),
    url(r'^search', search_view, name='search'),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe

from markdown_deux import markdown

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=220)
	content = models.TextField()
	image = models.FileField(null=True, blank=True)
	timestamp = models.DateTimeField(default=timezone.now)
	slug = models.SlugField(unique=True)

	def __str__(self):		
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={'slug' : self.slug })

	def markdown(self):	
		return mark_safe(markdown(self.content))


	class Meta:
		ordering = ["-timestamp"]

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

# Create your views here.
def list_view(request):         # list of recent posts

    query = Post.objects.all()
    paginator = Paginator(query, 5) # Show 5 posts per page
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    context = {

            'posts' : posts, 

    }


    return render(request, 'posts/index.html', context)


def detail_view(request, slug=None):

    post = get_object_or_404(Post, slug=slug)

    context = {

        'post' : post,
    }

    return render(request, 'posts/single.html', context)

def search_view(request):
    
    query = request.GET['q']

    results = Post.objects.filter(

                Q(title__icontains = query) |
                Q(content__icontains = query) 

        ).distinct()

    paginator = Paginator(results, 10) # Show 5 posts per page
    page = request.GET.get('page')

    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)    



    return render(request, 'posts/index.html', { 'posts' : results })

templates/posts/archives.html
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>Keep It Simple.</title>
	<meta name="description" content="">  
	<meta name="author" content="">

   <!-- mobile specific metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="css/default.css">
	<link rel="stylesheet" href="css/layout.css">  
	<link rel="stylesheet" href="css/media-queries.css">   

   <!-- Script
   ================================================== -->
	<script src="js/modernizr.js"></script>

   <!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="favicon.png" >

</head>

<body class="page">

   <!-- Header
   ================================================== -->
   <header id="top">

   	<div class="row">

   		<div class="header-content twelve columns">

		      <h1 id="logo-text"><a href="index.html" title="">Keep It Simple.</a></h1>
				<p id="intro">Put your awesome slogan here...</p>

			</div>			

	   </div>

	   <nav id="nav-wrap"> 

	   	<a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show Menu</a>
		   <a class="mobile-btn" href="#" title="Hide navigation">Hide Menu</a>

	   	<div class="row">    		            

			   	<ul id="nav" class="nav">
			      	<li><a href="index.html">Home</a></li>
			      	<li class="has-children"><a href="#">Dropdown</a>
	                  <ul>
	                     <li><a href="#">Submenu 01</a></li>
	                     <li><a href="#">Submenu 02</a></li>
	                     <li><a href="#">Submenu 03</a></li>
	                  </ul>
	               </li>
	               <li><a href="demo.html">Demo</a></li>	
	               <li class="current"><a href="archives.html">Archives</a></li>
			      	<li class="has-children"><a href="single.html">Blog</a>
							<ul>
	                     <li><a href="blog.html">Blog Entries</a></li>
	                     <li><a href="single.html">Single Blog</a></li>	                     
	                  </ul>
			      	</li>		      	
			      	<li><a href="page.html">Page</a></li>
			   	</ul> <!-- end #nav -->			   	 

	   	</div> 

	   </nav> <!-- end #nav-wrap --> 	     

   </header> <!-- Header End -->

   <!-- Content
   ================================================== -->
   <div id="content-wrap">

   	<div class="row">

   		<div id="main" class="eight columns">

   			<section class="page">					

					<h2>Archives.</h2> 
					
					<p class="lead">Lorem ipsum Nisi enim est proident est magna occaecat dolore proident eu ex sunt consectetur consectetur dolore enim nisi exercitation adipisicing magna culpa commodo deserunt ut do Ut occaecat. Lorem ipsum Veniam consequat quis.</p>					
					
					<div class="row archive-list">

						<div class="twelve columns">

							<h4>Last 10 Posts.</h4>	

				      	<ul>
				      		<li><a href="">Dolor irure velit commodo cillum sit nulla</a></li>
				      		<li><a href="">laborum mollit quis nostrud sed</a></li>
				      		<li><a href="">consequat occaecat fugiat in adipisicing</a></li>
				      		<li><a href="">qui labore cillum sit in tempor veniam consequat</a></li>
				      		<li><a href="">quis nostrud sed sed</a></li>
				      		<li><a href="">quis proident ullamco ut dolore</a></li>
				      		<li><a href="">Dolor irure velit commodo cillum sit nulla</a></li>
				      		<li><a href="">veniam dolor dolor irure velit commodo cillum</a></li>
				      		<li><a href="">Dolor irure velit commodo cillum sit nulla</a></li>
				      		<li><a href="">voluptate enim veniam consequat occaecat</a></li>
				      	</ul>								

						</div>

						<div class="twelve columns">

							<h4>Archives By Month.</h4>

					      	<ul>
					        		<li><a href="">July 2013</a></li>
					      		<li><a href="">August 2013</a></li>
					      		<li><a href="">September 2013</a></li>
					      		<li><a href="">October 2013</a></li>
					      		<li><a href="">November 2013</a></li>
					      		<li><a href="">December 2013</a></li>
					      	</ul>							

						</div>

					</div> <!-- end row -->			      	

			      <div class="row archive-list">
			      	
						<div class="twelve columns">

							<h4>Archives By Category.</h4>	

				      	<ul>
				      		<li><a href="">Wordpress</a></li>
				      		<li><a href="">Ghost</a></li>
				      		<li><a href="">Joomla</a></li>
				      		<li><a href="">Drupal</a></li>
				      		<li><a href="">Magento</a></li>
				      		<li><a href="">Uncategorized</a></li>
				      	</ul>
							

						</div>

						<div class="twelve columns">

							<h4>Site Map.</h4>	

				      	<ul>
				      		<li><a href="">Archives</a></li>
				      		<li><a href="">Home</a></li>
				      		<li><a href="">About Us</a></li>
				      		<li><a href="">Blog</a></li>
				      		<li><a href="">Demo</a></li>
				      		<li><a href="">Other Stuff</a></li>
				      	</ul>							

						</div>

			      </div>					

				</section> <!-- End page -->

   		</div> <!-- End main -->


   		<div id="sidebar" class="four columns">

   			<div class="widget widget_search">
                  <h3>Search</h3> 
                  <form action="#">

                     <input type="text" value="Search here..." onblur="if(this.value == '') { this.value = 'Search here...'; }" onfocus="if (this.value == 'Search here...') { this.value = ''; }" class="text-search">
                     <input type="submit" value="" class="submit-search">

                  </form>
               </div>

   			<div class="widget widget_categories group">
   				<h3>Categories.</h3> 
   				<ul>
						<li><a href="#" title="">Wordpress</a> (2)</li>
						<li><a href="#" title="">Ghost</a> (14)</li>
						<li><a href="#" title="">Joomla</a> (5)</li>
						<li><a href="#" title="">Drupal</a> (3)</li>
						<li><a href="#" title="">Magento</a> (2)</li>
						<li><a href="#" title="">Uncategorized</a> (9)</li>						
					</ul>
				</div>

				<div class="widget widget_text group">
					<h3>Widget Text.</h3>

   				<p>Lorem ipsum Ullamco commodo laboris sit dolore commodo aliquip incididunt fugiat esse dolor aute fugiat minim eiusmod do velit labore fugiat officia ad sit culpa labore in consectetur sint cillum sint consectetur voluptate adipisicing Duis irure magna ut sit amet reprehenderit.</p>

   			</div>

   			<div class="widget widget_tags">
               <h3>Post Tags.</h3>

               <div class="tagcloud group">
                	<a href="#">Corporate</a>
                  <a href="#">Onepage</a>
                  <a href="#">Agency</a>
                  <a href="#">Multipurpose</a>
                  <a href="#">Blog</a>
                  <a href="#">Landing Page</a>
                  <a href="#">Resume</a>
               </div>
                  
            </div>

            <div class="widget widget_popular">
               <h3>Popular Post.</h3>

               <ul class="link-list">
                  <li><a href="#">Sint cillum consectetur voluptate.</a></li>
                  <li><a href="#">Lorem ipsum Ullamco commodo.</a></li>
                  <li><a href="#">Fugiat minim eiusmod do.</a></li>                     
               </ul>
                  
            </div>
   			
   		</div> <!-- end sidebar -->

   	</div> <!-- end row -->

   </div> <!-- end content-wrap -->


   <!-- Footer
   ================================================== -->
   <footer>

      <div class="row"> 

      	<div class="twelve columns">	
				<ul class="social-links">
               <li><a href="#"><i class="fa fa-facebook"></i></a></li>
               <li><a href="#"><i class="fa fa-twitter"></i></a></li>
               <li><a href="#"><i class="fa fa-google-plus"></i></a></li>               
               <li><a href="#"><i class="fa fa-github-square"></i></a></li>
               <li><a href="#"><i class="fa fa-instagram"></i></a></li>
               <li><a href="#"><i class="fa fa-flickr"></i></a></li>               
               <li><a href="#"><i class="fa fa-skype"></i></a></li>
            </ul>			
      	</div>
      	
         <div class="six columns info">

            <h3>About Keep It Simple</h3> 

            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
            Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem
            nibh id elit. 
            </p>

            <p>Lorem ipsum Sed nulla deserunt voluptate elit occaecat culpa cupidatat sit irure sint 
            sint incididunt cupidatat esse in Ut sed commodo tempor consequat culpa fugiat incididunt.</p>

         </div>

         <div class="four columns">

            <h3>Photostream</h3>
            
            <ul class="photostream group">
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
               <li><a href="#"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
            </ul>           

         </div>

         <div class="two columns">
            <h3 class="social">Navigate</h3>

            <ul class="navigate group">
               <li><a href="#">Home</a></li>
               <li><a href="#">Blog</a></li>
               <li><a href="#">Demo</a></li>
               <li><a href="#">Archives</a></li>
               <li><a href="#">About</a></li>
            </ul>
         </div>

         <p class="copyright">&copy; Copyright 2014 Keep It Simple. &nbsp; Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>.</p>
        
      </div> <!-- End row -->

      <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#top"><i class="fa fa-chevron-up"></i></a></div>

   </footer> <!-- End Footer-->


   <!-- Java Script
   ================================================== -->
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="js/jquery-1.10.2.min.js"><\/script>')</script>
   <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>  
   <script src="js/main.js"></script>

</body>

</html>

templates/posts/common/pagination.html
			<!-- Pagination -->
			{% if posts.count > 5 %}
			<div class="container">
							<nav class="pagination add-bottom">

		 	{% if posts.has_previous %}
               <span class="page-numbers prev inactive">			       		
				      <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
				        prev
				      </a>
	    		</span>				      
			{% endif %}

			{% for page in posts.paginator.page_range %}

   	        <a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" 
   	        class="page-numbers {% if page == posts.number %}current{% endif %}">
   	        {{ page }}
   	        </a>

     		{% endfor %}

        	{% if posts.has_next %}
   	         <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="page-numbers next">Next</a>

		     </nav>
		    {% endif %}
			</div>

			{% endif %}

		    <!--/ Pagination -->

templates/posts/index.html
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>
<!-- loading STATIC_URL='/static/' from edoc.settings -->
{% load static  %}

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>Edoc</title>
	<meta name="description" content="">  
	<meta name="author" content="">

	<!-- mobile specific metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="{% static "css/default.css" %}">
	<link rel="stylesheet" href="{% static "css/layout.css" %}">  
	<link rel="stylesheet" href="{% static "css/media-queries.css" %}"> 

   <!-- Script
   ================================================== -->
	<script src="{% static "js/modernizr.js" %}"></script>
   <!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="{% static "images/logo.jpg" %}" >

</head>
<body>

   <!-- Header
   ================================================== -->
   <header id="top">

   	<div class="row">

   		<div class="header-content twelve columns">

		      <h1 id="logo-text"><a href="{% url 'posts:home' %}" title="">Edoc</a></h1>
				<p id="intro">Innovate <span class="meta-sep">&bull;</span> Achieve <span class="meta-sep">&bull;</span> Lead </p>

			</div>			

	   </div>

   <!-- Content
   ================================================== -->
   <div id="content-wrap">

   	<div class="row">

   		<div id="main" class="eight columns">

   		{% block content %}
   				{% include 'posts/common/pagination.html' %}

   			{% for post in posts %}

		   		<article class="entry">

						<header class="entry-header">

							<h2 class="entry-title">
								<a href="{{ post.get_absolute_url }}" title="">{{ post.title|upper }}</a>
							</h2> 				 
                     {% if post.image %}
                     <div class="entry-content-media">
                        <div class="post-thumb">
                           <img src="{{ post.image.url }}">
                        </div> 
                     </div>				
                     {% endif %}	
							<div class="entry-meta">
								<ul>
									<li>{{ post.timestamp|timesince }} ago</li>
									<span class="meta-sep">&bull;</span>								
									<li><a href="#" title="" rel="category tag">trial</a></li>
									<span class="meta-sep">&bull;</span>
									<li>Aman</li>
								</ul>
							</div> 
						 
						</header> 
						
						<div id = 'marked' class="entry-content">
							<p>{{ post.markdown|truncatechars_html:120 }}</p>
						</div> 

				</article> <!-- end entry -->          

			{% endfor %}
			{% include 'posts/common/pagination.html' %}

		{% endblock content %}

						

   		</div> <!-- end main -->

   		<div id="sidebar" class="four columns">

   			<div class="widget widget_search">
                  <h3>Search</h3> 
                  <form action="{% url 'posts:search' %}">

                     <input name="q" type="text" value="Search here..." onblur="if(this.value == '') { this.value = 'Search here...'; }" onfocus="if (this.value == 'Search here...') { this.value = ''; }" class="text-search">
                     <input type="submit" value="" class="submit-search">

                  </form>
               </div>   			
   		</div> <!-- end sidebar -->

   	</div> <!-- end row -->

   </div> <!-- end content-wrap -->

   <!-- Footer
   ================================================== -->
   <footer>

      <div class="row"> 

      	<div class="twelve columns">	
				<ul class="social-links">
               <li><a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
               <i class="fa fa-facebook"></i>
               </a></li>
               <li><a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'><i class="fa fa-google-plus"></i></a></li>          
            </ul>			
      	</div>
      	
         <div class="twelve columns info">

            <h3>About Me</h3> 

            <p>Edoc , reverse for Code, is just for my learning purposes.</p>

            <p>Thanks for your visit.</p>

         </div>

         <p class="copyright">&copy; Copyright 2017 Aman Agrawal. &nbsp;</p>
        
      </div> <!-- End row -->

      <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#top"><i class="fa fa-chevron-up"></i></a></div>

   </footer> <!-- End Footer-->


   <!-- Java Script
   ================================================== -->
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="{% static "js/jquery-1.10.2.min.js" %}"><\/script>')</script>
   <script type="text/javascript" src="{% static "js/jquery-migrate-1.2.1.min.js" %}"></script>  
   <script src="{% static "js/main.js" %}"></script>


</body>

</html>

templates/posts/single.html
{% extends 'posts/index.html' %}

    {% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

   			<article class="entry">

					<header class="entry-header">

						<h2 class="entry-title">
							{{ post.title }}
						
						</h2> 	
						<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>			

				
						<div class="entry-meta">
							<ul>
								<li>{{ post.timestamp }}</li>
								<span class="meta-sep">&bull;</span>							
								<li>
									<a href="#" title="" rel="category tag">trial</a>,
									<a href="#" title="" rel="category tag">try</a>  
								</li>
								<span class="meta-sep">&bull;</span>
								<li>Aman</li>
							</ul>
						</div> 
				 
					</header> 
				
                     {% if post.image %}
                     <div class="entry-content-media">
                        <div class="post-thumb">
                           <img src="{{ post.image.url }}">
                        </div> 
                     </div>				
                     {% endif %}	

					<div class="entry-content markdown-content">
					 
              {{ post.markdown }}

          </div>

				</article>

<div class="fb-comments"></div>

    {% endblock content %}